### ISSUE TITLE
Crash and no crash report( 

### ISSUE THREAD

**Issue by FilipKompaniets3** [Insane96/Stamina#1]
I installed insanelib latest version and I haven't played with other mods.

**Comment by Insane96** [comment]
Something's wrong with mixins. Also next time post logs, even if there is no crash log

**Comment by FilipKompaniets3** [comment]
Ок

**Comment by Insane96** [comment]
Fixed in 1.0.1

**Comment by FilipKompaniets3** [comment]
Thank tou
