### ISSUE TITLE
Stamina not regenerating?

### ISSUE THREAD

**Issue by Aceplante** [Insane96/Stamina#3]
**Versions**:
* Minecraft: 1.20.1
* Forge: 47.3.0
* Stamina: 1.1.1
* InsaneLib: 

**What Happens**:  
after dying, stamina does not seem to regenerate? meaning you are perpetually unable to sprint

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
probably

**Comment by Insane96** [comment]
Fixed in 1.1.2
